### GET request with cookie passed through headers
GET http://127.0.0.1:8888/tblCrawlStats/getFirstCrawlInfo?st_time=2024-04-09&ed_time=2024-04-10
Accept: application/json
X-User-Id: {{user-id}}
X-Token: {{user-token}}

> {%
    client.test("Test status code", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
>>! 123.json

### 获取国家，类目，平台 饼图
GET {{url}}/tblCrawlStats/getCrawlStatsPieData?st_time=2024-03-19&ed_time=2024-04-18&report=3
Accept: application/json
X-User-Id: {{user-id}}
X-Token: {{user-token}}


### 获取邮箱资源量
GET http://127.0.0.1:8888/tblKolResource/getKolResourceCrawlInfo?st_time=2024-01-01&ed_time=2024-04-10
Accept: application/json
X-User-Id: {{user-id}}
X-Token: {{user-token}}

### 获取出次数，有效数，更新数
GET http://127.0.0.1:8888/tblCrawlStats/getSummaryCrawlInfo?st_time=2024-01-01&ed_time=2024-04-10
Accept: application/json
X-User-Id: {{user-id}}
X-Token: {{user-token}}

### 获取清洗报表
GET http://127.0.0.1:8888/tblCrawlStats/getCleanList?st_time=2024-01-01&ed_time=2024-04-11
Accept: application/json
X-User-Id: {{user-id}}
X-Token: {{user-token}}

### 获取更新次数报表
GET http://127.0.0.1:8888/tblCrawlStats/getTotalResourceReportsList?st_time=2024-01-01&ed_time=2024-04-11
Accept: application/json
X-User-Id: {{user-id}}
X-Token: {{user-token}}

### 获取大事记
GET http://127.0.0.1:8888/e/getTblCrawlEventsList?st_time=2024-01-01&ed_time=2024-04-11&page=1&pageSize=3
Accept: application/json
X-User-Id: {{user-id}}
X-Token: {{user-token}}


### 获取总资源库数据情况
GET http://127.0.0.1:8888/tblCrawlStats/getTotalResourceInfo
Accept: application/json
X-User-Id: {{user-id}}
X-Token: {{user-token}}