### GET request with cookie passed through headers
GET http://127.0.0.1:8888/tblCrawlStats/getFirstCrawlInfo?st_time=2024-04-07&ed_time=2024-04-08
Accept: application/json
X-User-Id: {{user-id}}
X-Token: {{user-token}}

> {%
    client.test("Test status code", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
>>! 123.json